version: 2.1
executors:
  awscli:
    docker:
      - image: amazon/aws-cli
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_PAGER: ""
jobs:
  build-image:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      - CI: ""
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            sudo apt update
            sudo apt install -y nodejs npm python3
            sudo npm install n -g
            sudo n stable
            sudo apt purge -y nodejs npm
            npm install -g @angular/cli
            sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            node --version
            npm --version
            python3 -V
      - run:
          name: Build Frontend Application
          working_directory: src/frontend
          command: |
            npm install
            npm run build
            cp -rp dist/frontend ../../docker/build/
      - run:
          name: Prepare Backend Application
          command: cp -rp src/backend docker/build/
      - run:
          name: Build Frontend Docker Image
          working_directory: docker/build
          command: docker build -t ${DOCKER_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run:
          name: Run Containers
          command: |
            docker run -itd \
              -p 80:80 \
              -p 8000:8000 \
              --network bridge \
              ${DOCKER_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} \
              bash
      - save_cache:
          name: Save artfact cache
          key: docker-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - docker/build
  push-image:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      - BUILDX: https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
    steps:
      - checkout
      - restore_cache:
          name: Restore image cache
          key: docker-{{ .Environment.CIRCLE_SHA1 }}
          paths: ~/caches/images.tar
      - run:
          name: Create directory for Docker Buildx plugin binary
          command: mkdir -vp ~/.docker/cli-plugins/
      - run:
          name: Login Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Download Buildx
          command: curl --silent -L --output ~/.docker/cli-plugins/docker-buildx ${BUILDX}
      - run:
          name: Add permission to execute buildx
          command: chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run:
          name: Create docker driver
          command: |
            docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
            docker buildx create --name ${CIRCLE_PROJECT_REPONAME}
            docker buildx use ${CIRCLE_PROJECT_REPONAME}
      - run:
          name: Build and Push docker image to Docker Hub
          working_directory: docker/build
          command: docker buildx build --platform linux/amd64,linux/arm64 -t ${DOCKER_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} --push .
workflows:
  version: 2.1
  execproxy-pipeline:
    jobs:
      - build-image
      - push-image:
          requires:
            - build-image
          filters:
            branches:
              only:
                - main
